"""add_archive_and_stats_tables

Revision ID: 88dc6db9a2cf
Revises: f90fcaeceafa
Create Date: 2026-04-23 18:08:38.702410+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dc6db9a2cf'
down_revision: Union[str, None] = 'f90fcaeceafa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_archive',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('appeared', sa.Boolean(), nullable=True),
    sa.Column('check', sa.Integer(), nullable=True),
    sa.Column('original_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_archive_date', 'reservation_archive', ['date'], unique=False)
    op.create_index('ix_archive_venue', 'reservation_archive', ['venue_id'], unique=False)
    op.create_index(op.f('ix_reservation_archive_venue_id'), 'reservation_archive', ['venue_id'], unique=False)
    op.create_table('venue_stats_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('bookings', sa.Integer(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('came', sa.Integer(), nullable=False),
    sa.Column('no_show', sa.Integer(), nullable=False),
    sa.Column('peak_hour', sa.String(length=5), nullable=True),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'date', name='uq_stats_venue_date')
    )
    op.create_index('ix_stats_venue_date', 'venue_stats_daily', ['venue_id', 'date'], unique=False)
    op.create_index(op.f('ix_venue_stats_daily_venue_id'), 'venue_stats_daily', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venue_stats_daily_venue_id'), table_name='venue_stats_daily')
    op.drop_index('ix_stats_venue_date', table_name='venue_stats_daily')
    op.drop_table('venue_stats_daily')
    op.drop_index(op.f('ix_reservation_archive_venue_id'), table_name='reservation_archive')
    op.drop_index('ix_archive_venue', table_name='reservation_archive')
    op.drop_index('ix_archive_date', table_name='reservation_archive')
    op.drop_table('reservation_archive')
    # ### end Alembic commands ###
