"""add_venue_and_venue_role_models

Revision ID: f90fcaeceafa
Revises: 77b0649175d1
Create Date: 2026-04-21 07:55:01.406170+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90fcaeceafa'
down_revision: Union[str, None] = '77b0649175d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vk_group_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('owner_vk_id', sa.BigInteger(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('plan_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_vk_group_id'), 'venues', ['vk_group_id'], unique=True)
    op.create_table('venue_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('vk_user_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'vk_user_id', name='uq_venue_role_user')
    )
    op.create_index('ix_venue_role_user', 'venue_roles', ['vk_user_id'], unique=False)
    op.create_index(op.f('ix_venue_roles_venue_id'), 'venue_roles', ['venue_id'], unique=False)
    op.add_column('error_log', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_error_log_venue_id'), 'error_log', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'error_log', 'venues', ['venue_id'], ['id'], ondelete='SET NULL')
    op.add_column('rate_limit', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_rate_limit_venue_id'), 'rate_limit', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'rate_limit', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.add_column('reservation', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.add_column('reservation', sa.Column('extra_data', sa.JSON(), nullable=False))
    op.create_index('ix_reservation_venue', 'reservation', ['venue_id'], unique=False)
    op.create_index(op.f('ix_reservation_venue_id'), 'reservation', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'reservation', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    op.add_column('scheduled_task', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_scheduled_task_venue_id'), 'scheduled_task', ['venue_id'], unique=False)
    op.create_index('ix_task_venue', 'scheduled_task', ['venue_id'], unique=False)
    op.create_foreign_key(None, 'scheduled_task', 'venues', ['venue_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scheduled_task', type_='foreignkey')
    op.drop_index('ix_task_venue', table_name='scheduled_task')
    op.drop_index(op.f('ix_scheduled_task_venue_id'), table_name='scheduled_task')
    op.drop_column('scheduled_task', 'venue_id')
    op.drop_constraint(None, 'reservation', type_='foreignkey')
    op.drop_index(op.f('ix_reservation_venue_id'), table_name='reservation')
    op.drop_index('ix_reservation_venue', table_name='reservation')
    op.drop_column('reservation', 'extra_data')
    op.drop_column('reservation', 'venue_id')
    op.drop_constraint(None, 'rate_limit', type_='foreignkey')
    op.drop_index(op.f('ix_rate_limit_venue_id'), table_name='rate_limit')
    op.drop_column('rate_limit', 'venue_id')
    op.drop_constraint(None, 'error_log', type_='foreignkey')
    op.drop_index(op.f('ix_error_log_venue_id'), table_name='error_log')
    op.drop_column('error_log', 'venue_id')
    op.drop_index(op.f('ix_venue_roles_venue_id'), table_name='venue_roles')
    op.drop_index('ix_venue_role_user', table_name='venue_roles')
    op.drop_table('venue_roles')
    op.drop_index(op.f('ix_venues_vk_group_id'), table_name='venues')
    op.drop_table('venues')
    # ### end Alembic commands ###
